#!/usr/bin/env node
/* build-waf.mjs — turn cloudflare/blocklist.txt (+ allowlist.txt) into the
 * three moderation layers:
 *   1. functions/moderation.js     — substring regex + allow set (middleware)
 *   2. assets/js/moderation.js     — same, for the create form
 *   3. cloudflare/rule-expression.txt — Cloudflare Redirect Rule expression
 *
 * Matching model: BLOCK terms match as SUBSTRINGS (wildcard) — "murder" hits
 * "Murder Party". ALLOW phrases match the ENTIRE field value EXACTLY, so they
 * rescue clean phrases without ever opening a loophole.
 *
 *   node seo/tools/build-waf.mjs   (runs first in `npm run build`)
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");

const readList = (f) => existsSync(f)
  ? readFileSync(f, "utf8").split("\n").map((l) => l.trim().toLowerCase()).filter((l) => l && !l.startsWith("#"))
  : [];

const terms = [...new Set(readList(join(root, "cloudflare", "blocklist.txt")))];
/* allow phrases normalized the same way values are matched (collapse spaces/hyphens) */
const allow = [...new Set(readList(join(root, "cloudflare", "allowlist.txt")).map((s) => s.replace(/[\s_-]+/g, " ").trim()))];

/* ---- WHOLE-WORD TERMS ---------------------------------------------------
 * Substring matching is right for almost every term here, and deliberately so:
 * it is what makes evasion hard. But a handful of short roots are also the
 * insides of ordinary English words, and matching them anywhere blocks real
 * event names: "Grape Festival" (rape), "spice" (spic), "Killarney" (kill),
 * "raccoon" (coon), "Scunthorpe" (cunt), "assassin" aside, "Cockburn",
 * "Dickens", "Sussex", "analysis", "Weeden".
 *
 * These, and only these, are matched with word boundaries, and are left OUT of
 * the compaction regex — compacted text has no word boundaries to test, so
 * including them there would put the false positives straight back. Evasion
 * protection is weaker for these specific words; blocking a county fair is the
 * more likely harm on a site whose only remaining visitor-text surface is a
 * preview image's label. */
const WHOLE_WORD = new Set([
  "rape", "spic", "kill", "coon", "cunt", "anal", "dick", "sex", "hump",
  "boob", "poop", "crap", "fart", "turd", "snot", "weed", "wop", "dyke",
  "spaz", "negro", "darky", "queef", "prick", "hate", "shoot", "naked",
  "nude", "maim", "gook", "dago", "paki", "heeb", "twat",
]);
const isWholeWord = (t) => WHOLE_WORD.has(t.replace(/[^a-z0-9]/g, ""));

/* ---- substring regex source (layers 1 + 2) ----
 * Escape regex metachars; let spaces/hyphens in a term match any run of
 * whitespace/hyphens. Substring/wildcard match, except for WHOLE_WORD terms. */
const reSource = "(?:" + terms
  .map((t) => {
    const body = t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&").replace(/[\s-]+/g, "[\\s-]+");
    return isWholeWord(t) ? `\\b${body}\\b` : body;
  })
  .sort((a, b) => b.length - a.length)
  .join("|") + ")";

/* ---- compaction regex: defeats separator evasion (m.u.r.d.e.r, k i l l,
 * f-u-c-k). Matched against the value with ALL non-alphanumerics removed.
 * Only terms whose compacted length >= 5 are included, so joining two normal
 * words can't coincidentally spell a 1-3 char fragment. Floor is 4 so the
 * core terms (kill, fuck, rape, nazi, …) are evasion-protected; the rare
 * cross-word false positive ("this hit" -> "shit") is accepted over-blocking. */
const compactTerms = [...new Set(
  terms.filter((t) => !isWholeWord(t)).map((t) => t.replace(/[^a-z0-9]/g, "")).filter((t) => t.length >= 4)
)].sort((a, b) => b.length - a.length);
const compactSource = "(?:" + compactTerms.map((t) => t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|") + ")";

/* Dropping the whole-word terms from the compaction pass would give back the
 * evasion they most need protecting from — "k i l l", "r-a-p-e". So they get a
 * SECOND compaction regex, applied only when the value has the shape of
 * separator evasion in the first place (a run of single characters split by
 * punctuation or spaces). "Grape Festival" does not have that shape; "r-a-p-e"
 * does, and nobody writes a real event name that way. */
const strictTerms = [...new Set(
  terms.filter(isWholeWord).map((t) => t.replace(/[^a-z0-9]/g, "")).filter((t) => t.length >= 3)
)].sort((a, b) => b.length - a.length);
const strictSource = "(?:" + strictTerms.map((t) => t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|") + ")";

const banner = `/* GENERATED by seo/tools/build-waf.mjs from cloudflare/blocklist.txt + allowlist.txt — do not edit.
 * BLOCK_RE: substring match on normalized text (a short, high-collision root
 * such as "rape" or "kill" is anchored with \\b so "Grape Festival" and
 * "Killarney" are not blocked).
 * BLOCK_COMPACT_RE: substring match on the value with all non-alphanumerics
 * stripped (anti-evasion).
 * BLOCK_COMPACT_STRICT_RE: the whole-word roots, for compacted values only
 * when the raw value LOOKS separator-evaded ("k i l l", "r-a-p-e").
 * ALLOW: exact full-value rescue. */`;

/* the "someone is spelling it out" test, shared by both consumers */
const EVASION_SRC = "(?:^|[^a-z0-9])[a-z0-9](?:[^a-z0-9]+[a-z0-9]){2,}";

writeFileSync(join(root, "functions", "moderation.js"),
  `${banner}\nexport const BLOCK_RE = new RegExp(${JSON.stringify(reSource)}, "i");\n` +
  `export const BLOCK_COMPACT_RE = new RegExp(${JSON.stringify(compactSource)}, "i");\n` +
  `export const BLOCK_COMPACT_STRICT_RE = new RegExp(${JSON.stringify(strictSource)}, "i");\n` +
  `export const EVASION_RE = new RegExp(${JSON.stringify(EVASION_SRC)}, "i");\n` +
  `export const ALLOW = new Set(${JSON.stringify(allow)});\n`);

writeFileSync(join(root, "assets", "js", "moderation.js"),
  `${banner}\nwindow.AC_MOD_RE = new RegExp(${JSON.stringify(reSource)}, "i");\n` +
  `window.AC_MOD_COMPACT_RE = new RegExp(${JSON.stringify(compactSource)}, "i");\n` +
  `window.AC_MOD_COMPACT_STRICT_RE = new RegExp(${JSON.stringify(strictSource)}, "i");\n` +
  `window.AC_MOD_EVASION_RE = new RegExp(${JSON.stringify(EVASION_SRC)}, "i");\n` +
  `window.AC_MOD_ALLOW = ${JSON.stringify(allow)};\n`);

/* ---- Cloudflare Redirect Rule expression (layer 3, substring) ---- */
const esc = (w) => w.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
const checks = terms
  .map((w) => `(lower(url_decode(http.request.uri.query)) contains "${esc(w)}")`)
  .join(" or\n  ");
const expr =
  `(http.request.uri.path eq "/c" or http.request.uri.path eq "/c.html" or ` +
  `http.request.uri.path eq "/api/og" or http.request.uri.path contains "countdown") and (\n  ` +
  checks + `\n)`;
writeFileSync(join(root, "cloudflare", "rule-expression.txt"), expr + "\n");

console.log(`Moderation: ${terms.length} block terms, ${allow.length} allow phrases -> moderation.js (functions + assets) + cloudflare/rule-expression.txt`);
