/* class-ideas.mjs — the nine "things to actually do with this in a lesson"
 * cards. They lived on the home page's Classroom tab; when the tabs became
 * pages the tab's content moved to /classroom/ (build-classroom.mjs), and the
 * data moved here so it stays a plain, side-effect-free table. Each idea is
 * specific enough to run tomorrow, and each carries its own "where we took a
 * liberty" line — because a lesson built on a simulation should know which
 * parts are measurements and which are drawing decisions. */
import { BEACHBALL } from "./build-simulator.mjs";
import { LAUNCH_PATH as ROCKET_PATH } from "./solar-pages.mjs";

export const CLASS_IDEAS = [
  { ico: "timer", title: "Give time a size", href: "/timer/",
    idea: `Put a <a href="/timer/1-minute/">one-minute timer</a> on the board and ask the class to close their eyes and put a hand up when they think the minute is up. The spread is the lesson: hands go up from about 35 seconds to well past 90, and nobody believes that until they have seen it. Run it again after telling them the answer and watch the spread narrow — that is calibration, and it is the whole idea behind why we measure things instead of estimating them.`,
    honest: `The timer is honest about its own limits: a browser timer can drift if the tab is buried or the laptop sleeps, and <a href="/methodology/browser-timing/">we measured by how much</a> rather than assuming.` },
  { ico: "stopwatch", title: "Make them argue about an average", href: "/stopwatch/multiple/",
    idea: `<a href="/stopwatch/multiple/">Three stopwatches at once</a>, three groups, one repeated task — how long to fill a beaker, walk the length of the room, solve one long-division problem. Every lap is kept, and the fastest, slowest and mean are worked out for them. Then ask the question that matters: which of those three numbers should we report, and who does each one flatter?`,
    honest: `Laps are recorded to a hundredth of a second, which is real; whether a human thumb on a key is accurate to a hundredth of a second is not, and it is worth saying so out loud.` },
  { ico: "sunrise", title: "Why the days are getting longer", href: "/sun/",
    idea: `Open <a href="/sun/">your own town</a>, one far north — <a href="/sun/anchorage/">Anchorage</a> — and one near the equator — <a href="/sun/singapore/">Singapore</a> — and put the three day lengths side by side. Then step the date forward a month at a time using the date picker. Singapore barely moves. Yours swings by hours. Anchorage swings by most of a day. Ask them to explain it before you show them the <a href="/sun-moon-earth-movement-simulator/">tilted Earth</a> — the guesses are the good part.`,
    honest: `Every sunrise here is computed in the browser from the date and the place, never looked up, so any date works. It assumes a flat horizon: a mountain to your east will make the real sunrise later than the page says.` },
  { ico: "moon", title: "Predict tonight's moon, then go and check", href: "/moon/",
    idea: `Before a lesson on phases, ask each student to draw the shape they expect the moon to be tonight. Then open <a href="/moon/">the moon page</a> for your town. Then — and this is the part that sticks — set it forward a week and ask them to draw that one too, and give them a reason to go outside on the night and see whether they were right. A prediction that can be checked is a different thing from a fact that must be believed.`,
    honest: `The phase, the illumination and the rise and set times are solved from the real orbit for your location. The moon glyph is drawn from the real lunar near side at its real coordinates, so the dark patches are where they actually are.` },
  { ico: "earthmoon", title: "Stand the seasons up", href: "/sun-moon-earth-movement-simulator/",
    idea: `The <a href="/sun-moon-earth-movement-simulator/">Sun, Earth and Moon simulator</a> is set to your town and can be dragged through a day, a week or a month. Drag a single day and watch the lit half of the Earth turn under your city — that is a day. Then jump six months and do it again. The class can see that nothing about the Earth changed; only where it is standing did. Nearly every misconception about seasons dies right there. <strong>Then take them outside and build it.</strong> A ${BEACHBALL.ballCm} cm beach ball is the sun; the Earth is a ${BEACHBALL.earthMm.toFixed(1)} mm marble and the moon a ${BEACHBALL.moonMm.toFixed(1)} mm peppercorn held ${BEACHBALL.moonDistCm.toFixed(0)} cm from it — and the marble has to stand <strong>${BEACHBALL.sunDistM.toFixed(0)} metres</strong> away across the field. Two children can hold the whole Earth–moon system in their hands and still not be able to shout to the sun.`,
    honest: `<strong>This one is deliberately not to scale.</strong> The moon is drawn 23 times too close and the sun 3,151 times too close and 52 times too small, and the page prints those exact numbers rather than hiding them, because a picture that fits on a screen cannot also be to scale. What IS true: the directions, the phase, and which half of the Earth is lit.` },
  { ico: "solar", title: "Show them the shape they have never been shown", href: "/solar-system-simulator/",
    idea: `Every textbook diagram of the solar system is a lie of spacing — eight planets neatly spread across a page. Start the <a href="/solar-system-simulator/">solar system simulator</a> at the inner planets, then climb the zoom ladder one rung at a time to Neptune and Pluto. By the last rung the inner four are a single knot in the middle. Ask what that means for how long anything takes to get anywhere, and you have set up the <a href="${ROCKET_PATH}">launch window</a> lesson for free.`,
    honest: `The orbits are to scale within each view and the positions are solved when the page loads. The planets themselves are <em>not</em> to scale — at the Saturn view, Jupiter would be three thousandths of a pixel across. The dots are sized to be seen, and the page says so.` },
  { ico: "rocket", title: "Why you cannot just point at Mars", href: ROCKET_PATH,
    idea: `Ask the class how you would fly to Mars. Someone will say "point at it". Then open <a href="${ROCKET_PATH}">rocket launches</a> and show them the next real window, worked out live, and the fact that it only comes round every 26 months. The killer table is the one comparing what real missions did against the cheapest possible route: Voyager 2 reached Saturn 833 days FASTER than the cheapest route allows, because Jupiter threw it. Gravity assists stop being magic and become arithmetic.`,
    honest: `The flight paths drawn are minimum-energy transfers — the cheapest route, and the reference every real mission plan is measured against. They ignore orbital tilt and gravity assists, and the page states all three.` },
  { ico: "wave", title: "The moon, moving water, today", href: "/tides/",
    idea: `Tides are the one place a student can watch the moon do something to the Earth. Open <a href="/tides/">a station near you</a> — or any coast you have been to — and put today's curve on the board. Two highs, two lows, and they shift later each day by roughly the same amount the moon rises later each day. Then open the <a href="/sun-moon-earth-movement-simulator/">simulator</a> alongside and line the sun and moon up: that is a spring tide, and the curve on the tide page will be taller that week.`,
    honest: `These are astronomical predictions from NOAA — the sun and moon only. Real water is also pushed about by wind and air pressure, so the sea on the day can differ from the prediction, and this page never claims otherwise.` },
  { ico: "globe", title: "Where is it night right now?", href: "/world-clock/",
    idea: `Put the day-and-night map from the front page on the projector and ask who, right now, is asleep. Then ask why the line is not vertical — and let them work out that the tilt they learned about for the seasons is the same tilt bending that line. Finish by picking a country the class has a connection to and finding out what time it is there and whether anyone would answer the phone.`,
    honest: `The lit and dark halves are solved from the sun's real position and updated every minute in the browser. It is a flat map of a round Earth, so the shapes near the poles are stretched — which is itself a good question to ask a class.` },
];
