/* css-parts.mjs — the stylesheet as an ordered list of section files.
 *
 * assets/css/style.css was one 132KB monolith that every tool page inlined
 * whole: a timer page carried the alarm clock's 20KB, the tide tool's 11KB and
 * the home dashboard's 7KB for nothing. The source of truth is now
 * assets/css/parts/NN-name.css, each tagged with the SECTION it belongs to;
 * build-inline gives a page only the sections it actually renders.
 *
 * TWO RULES MAKE THIS SAFE, both enforced below rather than trusted:
 *
 * 1. Parts are emitted in numeric filename order — the order they were cut from
 *    the original file. What a page gets is a SUBSEQUENCE of the old cascade,
 *    never a reordering, so a rule that won before still wins.
 * 2. fullCss() must equal the old monolith byte for byte. assertLossless()
 *    checks it, so "nothing was dropped" is a test, not a claim.
 *
 * WHY THE CORE SLIVERS (04, 06, 09, 18): a handful of rules sit inside a widget's block
 * but are shared far beyond it — .tool-msg looks like timer furniture yet the
 * tide pages style their error line with it, and .timer-presets/.chip sit in the
 * tides search block yet every chip grid on the site uses them. A first pass
 * that shipped them with their neighbours broke chip layout on the sun pages,
 * the accent colour on tide errors, .tool-about spacing on the alarm and world
 * clock, and — worst — left the timer's Edit dialog completely unstyled, because
 * it reuses the alarm clock's .ac-dialog/.ac-form. Each is cut out IN PLACE as
 * its own `core` part, so the emitted order is untouched.
 *
 * Adding CSS: put it in the part for its section. A new section needs a new
 * numbered part plus an entry in SECTION_PROBES (build-inline.mjs), which is
 * what decides whether a page gets it.
 *
 * 01-themes.css is GENERATED by build-themes.mjs. style.css is generated too —
 * build-css.mjs folds the parts back into it, because the external <link>
 * fallback and social-card.mjs both still read that single file.
 */
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
export const root = join(here, "..", "..");
export const PARTS_DIR = join(root, "assets/css/parts");
export const MONOLITH = join(root, "assets/css/style.css");

/* [file, section]. ARRAY ORDER IS CASCADE ORDER — it is the order the rules had
 * in the original single stylesheet, and every later cut has been made in
 * place, so what a page receives is always a SUBSEQUENCE of that cascade.
 * (The line ranges each part was originally cut from used to live here for the
 * one-time splitFromMonolith() migration. They went stale the first time a part
 * was edited, and the parts have been the source of truth ever since;
 * assertLossless() is the invariant that actually matters.) */
const SPEC = [
  ["00-root.css", "core"],
  ["01-themes.css", "themes"],  /* GENERATED by build-themes */
  ["02-base.css", "core"],  /* shell, nav, cards, buttons, toplists, preset grids */
  /* The countdown display and the /work/ dashboard widgets used to sit inside
   * 02-base and so were inlined into all 3,000 pages. They are 24KB of rules
   * that 341 and 6 pages respectively can use. */
  ["02b-countdown.css", "countdown"],  /* .cd-*, the 420 pages' stage, the clock units */
  ["02c-work.css", "work"],  /* /work/ mc-* widgets + the boss screen */
  ["02d-faq.css", "core"],  /* .faq-card — event, tool and hub pages all carry one */
  ["02e-popout.css", "popout"],  /* Document Picture-in-Picture button (timer/stopwatch) */
  ["03-tools.css", "tools"],
  ["04-tool-msg.css", "core"],  /* .tool-msg — the tide pages style their error line with it */
  ["04b-tool-uses.css", "core"],  /* .tool-uses — the alarm-time pages carry this line with no tool on them */
  ["05-tools-b.css", "tools"],
  ["06-tool-about.css", "core"],  /* .tool-about — the alarm and world-clock pages have this card too */
  ["07-tools-c.css", "tools"],
  ["08-search.css", "search"],
  ["09-chips.css", "core"],  /* .timer-presets/.chip — every chip grid on the site */
  ["10-multitimer.css", "multitimer"],  /* the /timer/ hub's mt-* board — NOT the tides search */
  ["11-home.css", "home"],  /* mc-* mini-cards: homepage AND /work/ */
  ["12-egg.css", "egg"],
  ["13-hiw.css", "hiw"],
  ["14-worldclock.css", "worldclock"],
  ["15-alarm-top.css", "alarm"],
  ["16-seg.css", "seg"],  /* SHARED 7-segment display: see the note above */
  ["17-alarm.css", "alarm"],
  ["18-dialog.css", "core"],  /* .ac-dialog/.ac-form — the timer's Edit dialog reuses the alarm's */
  ["19-egg-shape.css", "egg"],
  ["20-content.css", "core"],  /* views, cta, privacy strip, byline */
  /* Same story as 02: the /sun/ page furniture and the event-page media rows
   * were unconditional. The crosslink strip (20c) and the small tail (20e/20g)
   * stay core because they are shared too widely to be worth a probe. */
  ["20b-sun.css", "sun"],   /* sun-* stat tiles + 7-day table */
  ["20c-xlink.css", "core"],  /* .xl-* related-astronomy strip: sun, moon AND tides */
  ["20d-sun2.css", "sun"],  /* sun dial, year chart, golden hour, hub minis */
  ["20d2-orrery.css", "orrery"],  /* the Sun-Earth-Moon view: /sun/ AND /moon/ place pages */
  ["20e-content2.css", "core"],  /* search dropdown, soon rail, calendar chips, rank lists */
  ["20f-event.css", "event"],  /* works chips, media tiles, song rows, artist module */
  ["20g-content3.css", "core"],  /* give-cta, tool-faq, .pl-facts */
  /* AHEAD OF tides AND moon, and that position is load-bearing. The home page
     defers those two sections to a second <style> at the end of body
     (DEFER_CSS in build-inline), which is only safe while they are the LAST
     sections in that page's cascade. The home page carries the time-difference
     card, so a timediff part sitting after them would either break that
     assertion or have to be deferred with them — and it styles a card high on
     the board, which would then paint unstyled and jump. Moving it here is
     free: every selector in the file is uniquely .tdiff-prefixed, so it
     collides with nothing and its cascade position cannot change an outcome. */
  ["20h-timediff.css", "timediff"],  /* the two-zone time-difference widget: /time-difference-calculator/ AND the home card */
  /* Same position, same reason as the part above it: every selector is uniquely
     .cv-prefixed, so its place in the cascade cannot change an outcome, and
     sitting AHEAD of tides + moon keeps the home page's deferred pair the last
     sections in any page's cascade (assertDeferIsSuffix in build-inline). */
  ["20i-clock-convert.css", "convert"],  /* the 12/24-hour converter: /24-hour-clock-converter/ + its per-time pages */
  /* Concept teasers (.hub-qs, .hub-teasers) sit high on /earth/, /time/, /space/
     and the hubs — above the tide and moon cards that /earth/ defers. Same
     move as timediff/convert: keep tides+moon the last two sections so
     DEFER_CSS on earth/index.html stays a suffix. */
  ["23-concept.css", "concept"],
  ["21-tides.css", "tides"],
  ["22-moon.css", "moon"],
];

export const PARTS = SPEC.slice();
export const SECTIONS = [...new Set(SPEC.map(([, s]) => s))];

const read = (f) => readFileSync(join(PARTS_DIR, f), "utf8");

/** Every part, in cascade order — byte-identical to the old style.css. */
export const fullCss = () => SPEC.map(([f]) => read(f)).join("\n");

/** Only the parts whose section is wanted, still in cascade order. */
export function composeCss(sections) {
  const want = new Set(sections);
  return SPEC.filter(([, sec]) => want.has(sec)).map(([f]) => read(f)).join("\n");
}

/** Throws unless the parts still reassemble into exactly `expected`. */
export function assertLossless(expected) {
  const got = fullCss();
  if (got !== expected) {
    const at = [...got].findIndex((c, i) => c !== expected[i]);
    throw new Error(`css parts no longer reassemble into style.css (first difference at char ${at})`);
  }
  const onDisk = readdirSync(PARTS_DIR).filter((f) => f.endsWith(".css")).sort().join();
  const named = SPEC.map(([f]) => f).sort().join();
  if (onDisk !== named) throw new Error(`assets/css/parts holds ${onDisk} but the manifest lists ${named}`);
}


/* ------------------------------------------------------------------ gate ---
 * WHICH SECTIONS COULD A PIECE OF MARKUP ACTUALLY USE?
 *
 * The probes in build-inline are hand-written regexes, and a wrong one is
 * invisible: the page renders, just unstyled somewhere nobody looked. This
 * derives the answer from the CSS itself instead — a section is needed when
 * one of its selectors could match, i.e. every class/id token in that single
 * selector is present in the markup. Compound selectors are respected, so
 * ".mc-widget .btn" needs BOTH, not just ".btn".
 *
 * build-inline asserts probes ⊇ this for every page it writes. Over-inclusion
 * is fine (a probe may be broader than strictly necessary); under-inclusion
 * fails the build. Element-only selectors (`body`, `h2`) are ignored — they
 * carry no token to test and always live in `core` anyway. */
const selCache = new Map();
function selectorsOf(file) {
  if (selCache.has(file)) return selCache.get(file);
  const css = read(file).replace(/\/\*[\s\S]*?\*\//g, " ");
  const out = [];
  for (const m of css.matchAll(/([^{}]+)\{/g)) {
    const prelude = m[1].trim();
    if (prelude.startsWith("@")) continue;
    for (const sel of prelude.split(",")) {
      const toks = [...sel.matchAll(/[.#]([A-Za-z_][\w-]*)/g)].map((x) => x[1]);
      if (toks.length) out.push(toks);
    }
  }
  selCache.set(file, out);
  return out;
}

/** class + id tokens used by a page's MARKUP (its own <style>/<script> ignored) */
export function markupTokens(html) {
  const body = html.replace(/<style[\s\S]*?<\/style>/gi, " ").replace(/<script[\s\S]*?<\/script>/gi, " ");
  const t = new Set();
  for (const m of body.matchAll(/\sclass="([^"]*)"/g)) for (const c of m[1].split(/\s+/)) if (c) t.add(c);
  for (const m of body.matchAll(/\sid="([^"]*)"/g)) t.add(m[1]);
  return t;
}

/** Sections whose CSS this markup could actually use. `core` is unconditional
 *  and `themes` is never selected, so neither is reported. */
export function sectionsNeeded(html) {
  const tok = markupTokens(html);
  const need = new Set();
  for (const [file, sec] of SPEC) {
    if (sec === "core" || sec === "themes" || need.has(sec)) continue;
    for (const s of selectorsOf(file)) {
      if (s.every((x) => tok.has(x))) { need.add(sec); break; }
    }
  }
  return need;
}

export const partsExist = () => existsSync(join(PARTS_DIR, "00-root.css"));
